global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'email-microservice'
    static_configs:
      - targets: ['email-microservice:7070']